src/renin/renin.ts

<h4>Repair screen rendering</h4>

Repair screen rendering

---

src/renin/renin.ts

<h4>Honor beatOffset in 4-bar-loop shortcut</h4>

Honor beatOffset in 4-bar-loop shortcut

---

package.json
yarn.lock

<h4>Upgrade three.js to r139</h4>

Upgrade three.js to r139

---

src/main.ts
src/renin/renin.ts
src/renin/ui/AudioBar.ts
src/renin/ui/UIAnimation.ts
src/renin/ui/performancePanel.glsl
src/renin/ui/performancePanelTexture.ts

<h4>Split demo rendering and ui rendering more in code</h4>
<hr />
<h4>Set up some renderer properties</h4>
<hr />
<h4>Stop rerendering UI when it is not needed</h4>
<hr />
<h4>Only apply tone mapping to demo, not UI</h4>
<hr />
<h4>Always use physically correct lights for everything</h4>
<hr />
<h4>Add legend to performance panel</h4>

Add legend to performance panel

---

src/renin/renin.ts
src/renin/ui/AudioBar.ts
src/renin/ui/performancePanelTexture.ts
src/renin/ui/thirdsOverlay.ts

<h4>Improve font rendering</h4>
<hr />
<h4>Improve lazy ui rendering scheme</h4>
<hr />
<h4>Remove uiUpdate from performance panel legend</h4>
<hr />
<h4>Ensure font is loaded for thirds overlay texture</h4>

Ensure font is loaded for thirds overlay texture

---

src/renin/ui/AudioBar.ts
src/renin/ui/UIBox.ts

<h4>Slightly round corners of ui box</h4>
<hr />
<h4>Remove unused import</h4>
<hr />
<h4>Fix typo</h4>
<hr />
<h4>Also round preview corners</h4>
<hr />
<h4>Add cache to rounded rectangle factory</h4>

Add cache to rounded rectangle factory

---

example-project/src/JumpingBox.ts
example-project/src/postfx.glsl

<h4>Further iterate on example project</h4>

Further iterate on example project

---

renin/package.json

<h4>Add bin to package.json</h4>
<hr />
<h4>Bump version</h4>

Bump version

---

renin/src/renin.ts

<h4>Add time to frame panel</h4>
<hr />
<h4>Improve demo resizing approach</h4>
<hr />
<h4>Properly jump to frame when panic-skipping frames</h4>
<hr />
<h4>Decrease panic skip threshold</h4>
<hr />
<h4>Properly dispose of dt when skipping</h4>
<hr />
<h4>Improve text rendering</h4>

Improve text rendering

---

renin/package.json

<h4>Bump version to 1.3.0</h4>

Bump version to 1.3.0

---

README.md

I guess the previous one was a guess

Correct URL to Vite.js

---

example-project/package.json
example-project/yarn.lock

<h4>Add typescript to example project</h4>

Add typescript to example project

---

renin/package.json

Bump to 1.4.0

---

renin/src/renin.ts

<h4>Make devicePixelRatio overridable by projects</h4>

Make devicePixelRatio overridable by projects

---

renin/src/ui/AudioBar.ts

<h4>Repair overlapping layers in layer overview</h4>

Repair overlapping layers in layer overview

---

renin/src/renin.ts
renin/src/sync.ts
renin/src/ui/AudioBar.ts
renin/src/ui/audioBarShader.glsl

<h4>Add support for non-4/4 time signatures</h4>

Add support for non-4/4 time signatures

---

renin/src/renin.ts

<h4>Fix pixel ratio independent frame panel rendering</h4>

Fix pixel ratio independent frame panel rendering

---

renin/src/renin.ts

<h4>Remove unused imports</h4>
<hr />
<h4>Improve fullscreen centering</h4>

Improve fullscreen centering

---

renin/package.json

<h4>Bump to version 2.2.0</h4>

Bump to version 2.2.0

---

renin/src/renin.ts

<h4>Add shortcuts for copying frame and step to clipboard</h4>
Now, you can press f and s to copy the current frame and step number to
the clipboard.

Add shortcuts for copying frame and step to clipboard

---

example-project/.gitignore
renin/src/cli.ts

<h4>Add git to init command</h4>

Add git to init command

---

example-project/package.json

<h4>Relax typescript version in example project</h4>

Relax typescript version in example project

---

renin/package.json
renin/yarn.lock

Upgrade dependencies

---

renin/src/ui/AudioBar.ts

Avoid overscrolling the audiobar

---

example-project/src/FlatLand.ts
example-project/src/SceneSwitcher.ts
example-project/src/SpinningDonut.ts

<h4>Add 2d scene to example project</h4>
This adds a bare-bones 2d canvas-based node to the example project.
This fixes ninjadev/renin#41 - Include simple canvas node in example
project.

Add 2d scene to example project

---

renin/src/renin.ts

Now it doesn't only cover the audiobar, but all tracks!
This fixes #38.

Expand vertical clickable area on tracks

---

example-project/package.json
example-project/src/SpinningDonut.ts
example-project/src/main.ts
example-project/vite.config.js

Oppdatere example-project til å funke med siste dependencies, og låse dependencies for å holde template stabil

Update example-project and lock dependencies

---

renin/package.json

<h4>Bump version to 2.3.0</h4>

Bump version to 2.3.0

---

renin/src/renin.ts

Surpress click handlers when fullscreen

---

renin/src/renin.ts

Remove remaining hard-coded beatsPerBar

---

README.md

This should help people who are new to the project, or like me who haven't run it for a time and are starting out on a fresh install get up to speed more quickly

README: Describe first time setup in a bit more detail

---

renin/src/renin.ts

<h4>Add sound to share video recordings</h4>

Add sound to share video recordings

---

example-project/src/main.ts
renin/src/renin.ts

<h4>Add aspect ratio support</h4>
Now demos can have custom aspect ratios.

Add aspect ratio support

---

example-project/docker-compose.yaml

I grew tired of copying it around from specific locations the second time I had to do it.

Add example docker compose

---

renin/package.json

<h4>Bump version to 2.4.0</h4>

Bump version to 2.4.0
