renin/src/renin.ts

<h4>Rerender current frame on live reload</h4>
This makes it easier to develop an effect while paused. Contrary to nin,
renin doesn't continuously rerender while paused. Therefore, we must
explicitly rerender on live reload instead.

Rerender current frame on live reload

---

renin/package.json
renin/src/ReninNode.ts
renin/src/renin.ts
renin/src/ui/screenShader.glsl
renin/src/ui/vite.ts
renin/src/utils.ts

<h4>Pass renin instance to node constructor</h4>
This way, we can do things with renin.renderer in the constructor of
nodes, if needed. This is a breaking change, since nodes will now need
to new up their children instead of just enumerating their classes.
<hr />
<h4>Rework sRGB/Linear color workflow</h4>
Maybe this is better? The idea is that textures are typically
interpreted as sRGB on load, then all operations and renders are linear,
then finally the very last rendering to the screen converts to sRGB
again.
In order to not completely crush colors, I found this only works well
with float rendertargets. Maybe that is a symptom of things not being
implemented properly? Or maybe that's just expected behavior? This is
probably not the last time we tweak color management in renin.
See …

Bump to version 2.0.0

---

renin/src/renin.ts
renin/src/ui/storedSettings.ts

This adds a bare-bones settings-helper on top of localstorage to make it
easy to read and write values that should be persisted, in a way that
does not get in the way of other things running on localhost:3000
This fixes #48.

Remember mute state across reloads

---

renin/src/renin.ts

It's not available, so this will just gracefully degrade the performance
panel a bit more without crashing the whole demo.

Ignore EXT_disjoint_timer_query_webgl2 in Firefox

---

renin/src/renin.ts

The API is only available in the Blink engine, so Firefox can't run the
demo when this crashes.
https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory

Don't crash on missing performance.memory

---

renin/src/renin.ts

<h4>Use Visibility API for update skippage</h4>
This should solve issues where music playback becomes choppy in dev mode
on slow machines -- and also switching back to a renin tab should be a
little faster now.

Use Visibility API for update skippage

---

renin/src/renin.ts
renin/src/ui/AudioBar.ts
renin/src/ui/performancePanelTexture.ts
renin/src/ui/thirdsOverlay.ts

<h4>Repair colors for texture-based UI parts</h4>
The colors in the UI were warped in the previous change to the color
management pipeline. This restores the original colors so that they work
with the new color management pipeline.

Repair colors for texture-based UI parts

---

renin/src/renin.ts

<h4>Add configurable max size for demo</h4>
Useful if you want to e.g. constrain demo size to 720p, for performance
reasons. Also useful for working in max 720p or smaller in fullscreen
mode during development on laptops.

Add configurable max size for demo

---

renin/src/renin.ts
renin/src/ui/AudioBar.ts

Issue #40 describes unwanted behavior of zooming on the center of the zoomed screen rather than on the global center of the timeline. I believe the actual issue of unwanted zooming to be the fact that zooming is always oriented around the playhead, which is often confusing.
This commit updates zooming to be oriented around the mouse cursor (since you use the mouse to zoom). Except for some rounding errors, which makes it perhaps not Perfect™, I think this feels quite natural, and therefore probably also fixes #40.

Zoom on mouse cursor instead of playhead

---

renin/package.json
renin/yarn.lock

This fixes an issue from f0ccb84ba4ed76013b2cbf1025dd67e9cd46c3f7, since it seems Vite.js is not yet compatible with rollup 3.x
I just kept getting the error:
> TypeError: Unknown file extension ".ts" for ~/Projects/renin/renin/rollup.config.ts

Downgrade rollup to 2.x again

---

.gitignore
renin/src/renin.ts

Dersom isFullscreen=false brukes samme oppløsning som preview-vinduet for å vise demoen i fullscreen i prod-bygg (man kan enklere se forskjellen ved å trykke enter under kjøring av prod-bygg). Ved å initialisere de til samme verdi får man riktig oppløsning

Set fullscreen when running in production mode

---

renin/src/ui/AudioBar.ts
renin/src/ui/UIBox.ts

<h4>Use BoxGeometry instead of BoxBufferGeometry</h4>
BoxBufferGeometry has been renamed to BoxGeometry in Three.js at some
point.

Use BoxGeometry instead of BoxBufferGeometry

---

renin/src/renin.ts

The TypeScript types already indicated that these fields are obligatory, but I guess it's nice to have renin not bootstrap a new project with type errors.

Make maxWidth/maxHeight optional

---

renin/src/music.ts

We only need to pause and call play again when we're actually currently playing. Calling pause when paused causes a crash (disconnecting the audionode twice).

Fix setting playback rate when paused

---

renin/src/sync.ts

I couldn't find any traces of us actually having used stepOffset before, so I can't say for sure what the intended purpose was, but this makes it behave more how I was expecting it, letting you offset when in a beat/bar flashes occur.
The trick is that we need the value for startStep to change exactly when we reach the step of its new value. That was out of sync without this fix, giving strange results.

Repair stepOffset in sync.flash

---

example-project/vite.config.js

This is needed in built demos so that they can be ran directly from the file system.

Make assets paths relative

---

renin/src/ReninNode.ts
renin/src/renin.ts

This matches the signature of render. I needed this to compute some beat dependent stuff in update. Although all nodes get renin through the constructor, so none need it explicitly really.

[Discussion] Explicitly pass renin to update

---

renin/package.json
renin/src/render.ts
renin/src/renin.ts

<h4>Add basic bring-your-own-encoder rendering</h4>
This adds a basic encoder-agnostic rendering function to renin, so that
you can render your demos to video.
To use this, you need to add some boilerplate/integration code to your
demo project. In your project, you can for instance use mp4-wasm as the
encoder. Here is a quick guide on how to do that.
First, install mp4-wasm:
```bash
yarn add mp4-wasm
```
Then, add these imports to the top of your demo's `main.ts`:
```typescript
import loadMP4Module from "mp4-wasm";
import mp4wasm from "mp4-wasm/build/mp4.wasm?url";
```
And finally, comment out `renin.loop()` in `main.ts` and instead do
something like this:
```typescript
// commented out for rendering purposes
// renin.loop()
(async () => {
const wasmBinary = await (await …
```

Add basic bring-your-own-encoder rendering

---

renin/src/ui/screenShader.glsl

<h4>Remove accidental double linear -> sRGB conversion</h4>
This fixes an issue where our demos would accidentally be the wrong
color.

Remove accidental double linear -> sRGB conversion

---

renin/src/renin.ts
renin/src/style.css

<h4>Add simple recording feature</h4>
This adds a simple recording feature -- press and hold 'r' to record a
short snippet of the demo for easy sharing in chats/social media. As far
as I can tell, MediaRecorder can only record the entire canvas, so we
need to do a little bit of work to temporarily disable the renin UI when
recording in order to only record the demo itself.
This is separate from the "perfect fps" video export rendering feature,
which is not quick, convenient and real-time in the same was as this is.

Add simple recording feature

---

renin/src/interpolations.ts

I used this a lot during crank, as i keep forgetting the manual implementation of a transition at a certain frame. I guess i could replace the lerp with a clamp.
The name i used for this function in crank was
'interpolateFrame',
Usage:
```
const letterGroup1ZPosition = easeIn(
smoothstep(
-100,
0,
interpolateFrame(frame, fadeDuration, 2489 - fadeDuration)
),
fadeDuration,
tFadeOut
);
const letterGroup2ZPosition = easeIn(
smoothstep(
-100,
0,
interpolateFrame(frame, fadeDuration, 2524 - fadeDuration)
),
fadeDuration,
tFadeOut
);
const letterGroup3ZPosition = easeIn(
smoothstep(
-100,
0,
interpolateFrame(frame, fadeDuration, 2560 - fadeDuration)
),
fadeDuration,
tFadeOut
);
```

Add transitionFromFrame

---

renin/src/renin.ts

<h4>Add debugTexture support</h4>
A very low-tech and un-fancy solution, but now you can quickly set
renin.debugTexture = myTexture to view that texture -- useful for
debugging purposes.

Add debugTexture support

---

example-project/src/main.ts
renin/src/renin.ts

<h4>Improve tone mapping strategy</h4>
Now, tonemapping is handled in userland instead, which is more flexible
and also probably more correct.

Improve tone mapping strategy

---

renin/src/renin.ts

<h4>Expose demoNeedsRender flag</h4>
This lets us rerender the demo from "userland", which is a requirement
for FlyControls.

Expose demoNeedsRender flag

---

example-project/src/FlatLand.ts

This fixes a bug where the canvas would stop animating after pressing enter to see the larger preview

Fix missing canvas texture update on resize in FlatLand in demo project
